name: Schedule Update
on:
  schedule:
    - cron:  '0 */3 * * *'
  workflow_dispatch:

jobs:
  pick_a_song:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Pick a song and commit it
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TOKEN: ${{ secrets.TOKEN }}
          PAT: ${{ secrets.PAT }}
        run: |
          python scripts/update.py
  
